### PR TITLE
Issue/686 part 1

### PR DESCRIPTION
**Pull request by bnordli**
Various fixes from ProCoSys #686 (see individual commits for coherent views)

### CODE REVIEW

**Comment by bnordli** [comment]
(Removed Resharper settings.)

**Comment by einari** [comment]
Could we take out the https://github.com/dolittle/Bifrost/pull/713/commits/037a238297ff07c257cffa244efd05a97be5fcee

I'd like to discuss this on its own. Not seeing the value of it immediately. The rest looks great! - As usual.. :) 

and also the 
https://github.com/dolittle/Bifrost/pull/713/commits/cbdfa52e111f42f24cdb5b7bcc9c7914bdf3dee6

This is a breaking change and would need to be in a separate pull request. I see that this needs changing and tied up to standards; OAUTH, JWT tokens. The tokens have all the information - claims - that could be used on the client instead.

**Comment by bnordli** [comment]
Yes, I can take out cbdfa52, and create a separate bug.

However, I'd like to keep 037a238. It is a continuation of what we discussed on Standup 1: That the entrance barrier to Bifrost is quite high, and that you need to peek around quite a bit to understand how to set it up, and you really don't have a place to start either. (We had multiple people on my previous project that complained about this.)

The `IConvention` is meant as a starting point to discover which conventions you can hook into. Also, this commit adds a lot of helpful documentation.

**Comment by einari** [comment]
Good point - also, having the base type, we could in fact visualize things in documentation more automatically - a tool that could traverse from the `IConvention` type. 

I'll pull the PR in and see whats conflicting and not quite building here tomorrow and consider this PR good when its all fine.

**Comment by einari** [comment]
2 Specs failing in JavaScript:

```text
for( assetsManager )
 describing( when getting scripts )
  it( should get scripts ) FAILED with message : Expected [  ] to be [ 'something.js', 'something_else.js' ].

for( assetsManager )
 describing( when initializing )
  it( should call server to get assets ) FAILED with message : Expected false to be true.

```

**Comment by bnordli** [comment]
Found dependencies between tests. This is not good.

The way Bifrost sets up global JS objects is not scalable (but I guess you know that already).

**Comment by einari** [comment]
It is not good at all. When we start transitioning the code to ES201x, a lot of clean up will have to happen and global state has to go. Fragility around tests like this is unacceptable. 

Thanks for catching and fixing it; again..

**Pull request merged**
