### PR TITLE
Issues/670 671

### PR DESCRIPTION
**Pull request by bnordli**
Fix for #670 and #671: Generate client proxies also for dynamically generated input validators. Separate between proxies for INotNullValidator and INotEmptyValidator.

### CODE REVIEW

**Comment by bnordli** [comment]
This is a sample command having one explicit input validator on documentNumber before this change:
```javascript
newEstimatingManual : Bifrost.commands.Command.extend(function() {
   var self = this;
   this._name = "newEstimatingManual";
   this._generatedFrom = "Domain.EstimatingManuals.List.NewEstimatingManual";
   this.estimatingManualId = ko.observable()
						  .extend({
							  type : "Number",
							  key : {"commandType":"Domain.EstimatingManuals.List.NewEstimatingManual","propertyName":"estimatingManualId"}
						  });
   this.documentNumber = ko.observable()
						  .extend({
							  type : "String",
							  validation : {"required":{"message":"'DocumentNumber' must not be empty."},"length":{"min":1,"max":64,"message":"DocumentNumber must be between {0} and {1} characters."}}
						  });
}),
```
And after this change having no explicit input validators at all
```javascript
newEstimatingManual : Bifrost.commands.Command.extend(function() {
   var self = this;
   this._name = "newEstimatingManual";
   this._generatedFrom = "Domain.EstimatingManuals.List.NewEstimatingManual";
   this.estimatingManualId = ko.observable()
						  .extend({
							  type : "Number",
							  validation : {"notNull":{"message":"'EstimatingManualId' must not be empty."},"greaterThan":{"value":0,"message":"The Value '{0}' for 'EstimatingManualId' is invalid."}},
							  key : {"commandType":"Domain.EstimatingManuals.List.NewEstimatingManual","propertyName":"estimatingManualId"}
						  });
   this.documentNumber = ko.observable()
						  .extend({
							  type : "String",
							  validation : {"notNull":{"message":"'DocumentNumber' must not be empty."},"length":{"min":1,"max":64,"message":"DocumentNumber must be between {0} and {1} characters."}}
						  });
}),
```

The changes in ICommand{Input,Business}Validator are needed because previously, CommandValidatorProvider only returned Bifrost.Validation.ICanValidate, while ValidationMetaDataGenerator worked with FluentValidation.IValidator. So we needed to consolidate the two validation interfaces. (All command validators inherit from the abstract Command{Input,Business}Validator, which implements both of these interfaces anyways.)

**Comment by bnordli** [comment]
Happy New Year!

Any hope this can be accepted, or discussed, soon?

**Comment by einari** [comment]
Happy New Year! 

Sorry about the delay here - busy times. 

Looks good, I'm accepting the pull request

**Comment by bnordli** [comment]
Thanks a lot!

Would you mind creating a new release also, so we can start using this new code? (I know we can just run from our fork, but it feels kind of better to stick to the official version.)

**Comment by einari** [comment]
On its way now, finally.. Sorry about the sluggish response!
Should really automate this...

**Pull request merged**
