### PR TITLE
Missed unneeded reference to System.Web.Optimization

### PR DESCRIPTION
**Pull request by bnordli**
I missed a spot (sorry). Just for a better future, no need to make a new release.

### CODE REVIEW

**Comment by bnordli** [comment]
Hmm.. maybe this is neede after all. Will investigate further.

**Comment by bnordli** [comment]
System.Web.Optimization was used by WebContext.HasRouteForCurrentRequest, which currently only was used by SinglePageApplication. (And System.Web.Optimization depends on WebGrease, which depends on Antlr.)

So if these references are to be removed, the bundle support has to go. IMO, this is the correct fix (no need to support bundles out of the box if it is not used by Bifrost), but it is a breaking change for SinglePageApplications using bundles in client code.

The other alternative is to revert 21497fd so that everything is fine again.

Your call, Einar! (And sorry for the confusion.)

**Comment by einari** [comment]
Ahh.. Thats right.  We need that. The way it works today the SinglePageApp stuff checks for existing routes and lets these go through. Basically the default behavior is to hijack all requests except for those with defined routes.

I'll revert and push a new version.

**Comment by bnordli** [comment]
Replaced by #678.

**Pull request closed without merging**
